service: lambda-http-get

provider:
  name: aws
  runtime: nodejs10.x
  region: sa-east-1

functions:
  hello:
    handler: handler.index
    events:
      - http:
          path: users/create
          method: get
